name: ioenv
channels : 
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - geopandas
  - matplotlib
  - numpy
  - mpl_toolkits
  - datetime
  - csv
  - obspy
  - math
  - requests
  - lxml
  - os
  - boto3
